/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program_uap_datanilai;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author TOSHIBA
 */
public class Form_Kelas9 extends javax.swing.JFrame {

    /**
     * Creates new form Form_Kelas9
     */
    public Form_Kelas9() {
        initComponents();
        this.setLocationRelativeTo(null);
        tampil_data();
    }
 private DefaultTableModel tabmode;
    
    public void tampil_data(){
        Object []baris = {"NIS","Nama","Bahasa Indonesia","IPA","Matematika","Bahasa Inggris"};
        tabmode = new DefaultTableModel(null, baris);
        tabeldata2.setModel(tabmode);
        Connection con = new KoneksiDB().ConnectDb();
        try {
            String sql = "select * from kelas_9 order by NIS asc";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String Nis = hasil.getString("NIS");
                String Nama = hasil.getString("NAMA");
                String B_indo = hasil.getString("BAHASA_INDONESIA");
                String Ipa = hasil.getString("IPA");
                String Mtk = hasil.getString("MATEMATIKA");
                String B_ing = hasil.getString("BAHASA_INGGRIS");
                String[] data = {Nis,Nama,B_indo,Ipa,Mtk,B_ing};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void reset(){
        nis2.setText("");
        nama2.setText("");
        bind2.setText("");
        ipa2.setText("");
        mtk2.setText("");
        bing2.setText("");
    }
    private void kliktable(){
        int baris = tabeldata2.getSelectedRow();
        nis2.setText((String)tabeldata2.getValueAt(baris, 0));
        nama2.setText((String)tabeldata2.getValueAt(baris, 1));
        bind2.setText((String)tabeldata2.getValueAt(baris, 2));
        ipa2.setText((String)tabeldata2.getValueAt(baris, 3));
        mtk2.setText((String)tabeldata2.getValueAt(baris, 4));
        bing2.setText((String)tabeldata2.getValueAt(baris, 5));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nis2 = new javax.swing.JTextField();
        nama2 = new javax.swing.JTextField();
        bind2 = new javax.swing.JTextField();
        ipa2 = new javax.swing.JTextField();
        mtk2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata2 = new javax.swing.JTable();
        btn_simpan2 = new javax.swing.JButton();
        btn_reset2 = new javax.swing.JButton();
        btn_ubah2 = new javax.swing.JButton();
        btn_hapus2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        bing2 = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Data Kelas 9");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("HALAMAN EDIT DATA SISWA KELAS 9");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 25, -1, -1));

        jLabel2.setText("NIS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 81, 85, -1));

        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 119, 85, -1));

        jLabel4.setText("Bahasa Indonesia");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 157, -1, -1));

        jLabel5.setText("IPA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 195, -1, -1));

        jLabel6.setText("Matematika");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 233, -1, -1));
        jPanel1.add(nis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 78, 170, -1));
        jPanel1.add(nama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 116, 170, -1));
        jPanel1.add(bind2, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 154, 170, -1));
        jPanel1.add(ipa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 192, 170, -1));
        jPanel1.add(mtk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 230, 170, -1));

        tabeldata2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeldata2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldata2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeldata2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 78, 743, 322));

        btn_simpan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_uap_datanilai/gambar/add2.png"))); // NOI18N
        btn_simpan2.setText("Simpan");
        btn_simpan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_simpan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 319, -1, -1));

        btn_reset2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_uap_datanilai/gambar/reset.JPG"))); // NOI18N
        btn_reset2.setText("Reset");
        btn_reset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reset2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reset2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 318, -1, -1));

        btn_ubah2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_uap_datanilai/gambar/file-edit-16x16.png"))); // NOI18N
        btn_ubah2.setText("Ubah  ");
        btn_ubah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubah2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ubah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 375, -1, -1));

        btn_hapus2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_uap_datanilai/gambar/exit.png"))); // NOI18N
        btn_hapus2.setText("Hapus");
        btn_hapus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hapus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 375, -1, -1));

        jLabel7.setText("Bahasa Inggris");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 271, -1, -1));
        jPanel1.add(bing2, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 268, 170, -1));

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_uap_datanilai/gambar/back.JPG"))); // NOI18N
        btn_back.setText("Kembali");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1037, 443, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_uap_datanilai/gambar/bg3.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1180, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan2ActionPerformed
        // TODO add your handling code here:
        if(nis2.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Tolong Masukkan NIS");
            } else if(nama2.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Tolong Masukkan Nama");
            } else if(bind2.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Tolong Masukkan Nilai Bahasa Indonesia");
            }else if(ipa2.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Tolong Masukkan Nilai IPA");
            }else if(mtk2.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Tolong Masukkan Nilai Matematika");
            }else if(bing2.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Tolong Masukkan Nilai Bahasa Inggris");
            }else{
        
        String NIS="", NAMA="", BAHASA_INDONESIA="", IPA="", MATEMATIKA="", BAHASA_INGGRIS="";
       
        NIS = nis2.getText();
        NAMA = nama2.getText();
        BAHASA_INDONESIA = bind2.getText();
        IPA = ipa2.getText();
        MATEMATIKA = mtk2.getText();
        BAHASA_INGGRIS = bing2.getText();
        
        try {
            Connection con = new KoneksiDB().ConnectDb();
            String sql = "insert into kelas_9 values (?,?,?,?,?,?)";
            PreparedStatement stat = (PreparedStatement) con.prepareStatement(sql);
            stat.setString(1, NIS);
            stat.setString(2, NAMA);
            stat.setString(3, BAHASA_INDONESIA);
            stat.setString(4, IPA);
            stat.setString(5, MATEMATIKA);
            stat.setString(6, BAHASA_INGGRIS);
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Menyimpan data BERHASIL","Informasi", JOptionPane.INFORMATION_MESSAGE);
            tampil_data();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE); 
        }
            }
    }//GEN-LAST:event_btn_simpan2ActionPerformed

    private void btn_ubah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubah2ActionPerformed
        // TODO add your handling code here:
        Connection con = new KoneksiDB().ConnectDb();
        String NIS="", NAMA="", BAHASA_INDONESIA="", IPA="", MATEMATIKA="", BAHASA_INGGRIS="";
        
        NIS = nis2.getText();
        NAMA = nama2.getText();
        BAHASA_INDONESIA = bind2.getText();
        IPA = ipa2.getText();
        MATEMATIKA = mtk2.getText();
        BAHASA_INGGRIS = bing2.getText();
        
        String sql="update kelas_9 set NAMA=?, BAHASA_INDONESIA=? ,IPA=?, MATEMATIKA=?,"
                + "BAHASA_INGGRIS=? where NIS='"+NIS+"'";
            java.sql.PreparedStatement stat = null;
            try {
                stat = con.prepareStatement(sql);
                stat.setString(1, NAMA);
                stat.setString(2, BAHASA_INDONESIA);
                stat.setString(3, IPA);
                stat.setString(4, MATEMATIKA);
                stat.setString(5, BAHASA_INGGRIS);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data BERHASIL di Ubah");
                tampil_data();
                reset();
            }catch(SQLException se){
                JOptionPane.showMessageDialog(null,"Data Gagal DiUbah");
            }   
    }//GEN-LAST:event_btn_ubah2ActionPerformed

    private void btn_hapus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus2ActionPerformed
        // TODO add your handling code here:
        int baris = tabeldata2.getSelectedRow();
        String nis = tabmode.getValueAt(baris, 0).toString();
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Anda yakin ingin menghapus data siswa \n NIS :"+nis+"?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(ok==0){
            try{
                //panggil method koneksi
                Connection con = new KoneksiDB().ConnectDb();
                String sql="delete from kelas_9 where NIS ='"+nis+"'";
                Statement st = con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Data Berhasil di hapus");
                tampil_data();
                reset();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Data Gagal di hapus");
            }
        }
    }//GEN-LAST:event_btn_hapus2ActionPerformed

    private void btn_reset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reset2ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btn_reset2ActionPerformed

    private void tabeldata2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldata2MouseClicked
        // TODO add your handling code here:
        kliktable();
    }//GEN-LAST:event_tabeldata2MouseClicked

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Kelas9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Kelas9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Kelas9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Kelas9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Kelas9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bind2;
    private javax.swing.JTextField bing2;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_hapus2;
    private javax.swing.JButton btn_reset2;
    private javax.swing.JButton btn_simpan2;
    private javax.swing.JButton btn_ubah2;
    private javax.swing.JTextField ipa2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mtk2;
    private javax.swing.JTextField nama2;
    private javax.swing.JTextField nis2;
    private javax.swing.JTable tabeldata2;
    // End of variables declaration//GEN-END:variables
}
