/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program_uap_datanilai;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TOSHIBA
 */
public class Form_Kelas7 extends javax.swing.JFrame {

    /**
     * Creates new form Form_Kelas7
     */
    public Form_Kelas7() {
        initComponents();
        this.setLocationRelativeTo(null);
        tampil_data();
    }
 private DefaultTableModel tabmode;
    
    public void tampil_data(){
        Object []baris = {"NIS","Nama","Bahasa Indonesia","IPA","Matematika","Bahasa Inggris"};
        tabmode = new DefaultTableModel(null, baris);
        tabeldata.setModel(tabmode);
        Connection con = new KoneksiDB().ConnectDb();
        try {
            String sql = "select * from kelas_7 order by NIS asc";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String Nis = hasil.getString("NIS");
                String Nama = hasil.getString("NAMA");
                String B_indo = hasil.getString("BAHASA_INDONESIA");
                String Ipa = hasil.getString("IPA");
                String Mtk = hasil.getString("MATEMATIKA");
                String B_ing = hasil.getString("BAHASA_INGGRIS");
                String[] data = {Nis,Nama,B_indo,Ipa,Mtk,B_ing};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void reset(){
        nis.setText("");
        nama.setText("");
        bind.setText("");
        ipa.setText("");
        mtk.setText("");
        bing.setText("");
    }
    private void kliktable(){
        int baris = tabeldata.getSelectedRow();
        nis.setText((String)tabeldata.getValueAt(baris, 0));
        nama.setText((String)tabeldata.getValueAt(baris, 1));
        bind.setText((String)tabeldata.getValueAt(baris, 2));
        ipa.setText((String)tabeldata.getValueAt(baris, 3));
        mtk.setText((String)tabeldata.getValueAt(baris, 4));
        bing.setText((String)tabeldata.getValueAt(baris, 5));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nis = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        bind = new javax.swing.JTextField();
        ipa = new javax.swing.JTextField();
        mtk = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        btn_simpan = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        bing = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Data Kelas 7");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("HALAMAN EDIT DATA SISWA KELAS 7");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 30, -1, -1));

        jLabel2.setText("NIS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 81, 85, -1));

        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 119, 85, -1));

        jLabel4.setText("Bahasa Indonesia");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 157, -1, -1));

        jLabel5.setText("IPA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 195, -1, -1));

        jLabel6.setText("Matematika");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 233, -1, -1));
        jPanel1.add(nis, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 78, 180, -1));
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 116, 180, -1));
        jPanel1.add(bind, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 154, 180, -1));
        jPanel1.add(ipa, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 192, 180, -1));
        jPanel1.add(mtk, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 230, 180, -1));

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeldata);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 78, 743, 322));

        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_uap_datanilai/gambar/add2.png"))); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 319, -1, -1));

        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_uap_datanilai/gambar/reset.JPG"))); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 318, -1, -1));

        btn_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_uap_datanilai/gambar/file-edit-16x16.png"))); // NOI18N
        btn_ubah.setText("Ubah  ");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 375, -1, -1));

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_uap_datanilai/gambar/exit.png"))); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 375, -1, -1));

        jLabel7.setText("Bahasa Inggris");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 271, -1, -1));
        jPanel1.add(bing, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 268, 180, -1));

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_uap_datanilai/gambar/back.JPG"))); // NOI18N
        btn_back.setText("Kembali");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1022, 444, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_uap_datanilai/gambar/bg3.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1160, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        if(nis.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Tolong Masukkan NIS");
            } else if(nama.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Tolong Masukkan Nama");
            } else if(bind.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Tolong Masukkan Nilai Bahasa Indonesia");
            }else if(ipa.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Tolong Masukkan Nilai IPA");
            }else if(mtk.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Tolong Masukkan Nilai Matematika");
            }else if(bing.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Tolong Masukkan Nilai Bahasa Inggris");
            }else{
        
        String NIS="", NAMA="", BAHASA_INDONESIA="", IPA="", MATEMATIKA="", BAHASA_INGGRIS="";
       
        NIS = nis.getText();
        NAMA = nama.getText();
        BAHASA_INDONESIA = bind.getText();
        IPA = ipa.getText();
        MATEMATIKA = mtk.getText();
        BAHASA_INGGRIS = bing.getText();
        
        try {
            Connection con = new KoneksiDB().ConnectDb();
            String sql = "insert into kelas_7 values (?,?,?,?,?,?)";
            PreparedStatement stat = (PreparedStatement) con.prepareStatement(sql);
            stat.setString(1, NIS);
            stat.setString(2, NAMA);
            stat.setString(3, BAHASA_INDONESIA);
            stat.setString(4, IPA);
            stat.setString(5, MATEMATIKA);
            stat.setString(6, BAHASA_INGGRIS);
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Menyimpan data BERHASIL","Informasi", JOptionPane.INFORMATION_MESSAGE);
            tampil_data();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE); 
        }
            }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        Connection con = new KoneksiDB().ConnectDb();
        String NIS="", NAMA="", BAHASA_INDONESIA="", IPA="", MATEMATIKA="", BAHASA_INGGRIS="";
        
        NIS = nis.getText();
        NAMA = nama.getText();
        BAHASA_INDONESIA = bind.getText();
        IPA = ipa.getText();
        MATEMATIKA = mtk.getText();
        BAHASA_INGGRIS = bing.getText();
        
        String sql="update kelas_7 set NAMA=?, BAHASA_INDONESIA=? ,IPA=?, MATEMATIKA=?,"
                + "BAHASA_INGGRIS=? where NIS='"+NIS+"'";
            java.sql.PreparedStatement stat = null;
            try {
                stat = con.prepareStatement(sql);
                stat.setString(1, NAMA);
                stat.setString(2, BAHASA_INDONESIA);
                stat.setString(3, IPA);
                stat.setString(4, MATEMATIKA);
                stat.setString(5, BAHASA_INGGRIS);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data BERHASIL di Ubah");
                tampil_data();
                reset();
            }catch(SQLException se){
                JOptionPane.showMessageDialog(null,"Data Gagal DiUbah");
            }   
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int baris = tabeldata.getSelectedRow();
        String nis = tabmode.getValueAt(baris, 0).toString();
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Anda yakin ingin menghapus data siswa \n NIS :"+nis+"?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(ok==0){
            try{
                //panggil method koneksi
                Connection con = new KoneksiDB().ConnectDb();
                String sql="delete from kelas_7 where NIS ='"+nis+"'";
                Statement st = con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Data Berhasil di hapus");
                tampil_data();
                reset();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Data Gagal di hapus");
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void tabeldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldataMouseClicked
        // TODO add your handling code here:
        kliktable();
    }//GEN-LAST:event_tabeldataMouseClicked

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Kelas7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Kelas7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Kelas7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Kelas7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Kelas7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bind;
    private javax.swing.JTextField bing;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JTextField ipa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mtk;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nis;
    private javax.swing.JTable tabeldata;
    // End of variables declaration//GEN-END:variables
}
